import type { ParamDef, FwTab } from "../fwParams";

export const llamaTabs: FwTab[] = [
  { key: "basic", label: "基本" },
  { key: "gpu", label: "GPU 与显存" },
  { key: "sampling", label: "采样" },
  { key: "rope", label: "上下文与 RoPE" },
  { key: "spec", label: "投机解码" },
  { key: "server", label: "服务与高级" },
];

const llamaKvTypes = ["f32", "f16", "bf16", "q8_0", "q4_0", "q4_1", "iq4_nl", "q5_0", "q5_1"];

export const llamaParams: ParamDef[] = [
  // —— 基本 ——
  { key: "bin", label: "命令", type: "text", default: "llama-server", nativeOnly: true, tab: "basic", desc: "llama-server 可执行文件路径；裸命令名会自动回退到一键安装目录" },
  { key: "ngl", label: "GPU 层数", type: "number", default: 99, tab: "basic", flag: "-ngl", desc: "放入 GPU 显存的最大层数；99 = 全部卸载" },
  { key: "ctxSize", label: "上下文长度", type: "number", default: 4096, tab: "basic", flag: "-c", desc: "提示词上下文窗口大小；0 = 使用模型自带默认值" },
  { key: "nPredict", label: "预测 token 数", type: "number", min: -1, tab: "basic", flag: "-n", placeholder: "默认 -1（无限）", desc: "本次生成最大 token 数；-1 = 不限制" },
  { key: "threads", label: "CPU 线程", type: "number", min: -1, tab: "basic", flag: "-t", placeholder: "默认 -1（自动）", desc: "生成使用的 CPU 线程数；填 0 或负数 = 自动" },
  { key: "threadsBatch", label: "批处理线程", type: "number", min: -1, tab: "basic", flag: "-tb", desc: "提示词/批处理阶段线程数；默认与 -t 相同" },
  { key: "batchSize", label: "批大小", type: "number", min: 1, tab: "basic", flag: "-b", placeholder: "默认 2048", desc: "逻辑最大批大小" },
  { key: "ubatchSize", label: "子批大小", type: "number", min: 1, tab: "basic", flag: "-ub", placeholder: "默认 512", desc: "物理最大子批大小" },
  { key: "parallel", label: "并行槽位", type: "number", min: -1, tab: "basic", flag: "-np", placeholder: "默认 -1（自动）", desc: "服务端并行槽位（并发会话）数；-1 = 自动" },
  { key: "keep", label: "保留前缀 token", type: "number", min: 0, tab: "basic", flag: "--keep", placeholder: "默认 0", desc: "初始提示词中保留的 token 数（-1 = 全部）" },

  // —— GPU 与显存 ——
  { key: "flashAttn", label: "Flash Attention", type: "select", options: ["auto", "on", "off"], default: "auto", tab: "gpu", flag: "--flash-attn", desc: "Flash Attention 加速；auto = GPU 支持时启用（官方默认 auto）" },
  { key: "cacheTypeK", label: "KV 缓存 K 类型", type: "select", options: llamaKvTypes, default: "f16", tab: "gpu", flag: "--cache-type-k", desc: "KV 缓存 K 部分数据类型；低精度省显存（官方默认 f16）" },
  { key: "cacheTypeV", label: "KV 缓存 V 类型", type: "select", options: llamaKvTypes, default: "f16", tab: "gpu", flag: "--cache-type-v", desc: "KV 缓存 V 部分数据类型；低精度省显存（官方默认 f16）" },
  { key: "kvOffload", label: "KV 卸载", type: "switch", default: true, tab: "gpu", flag: "--no-kv-offload", desc: "KV 缓存 GPU 卸载（默认启用；关闭时输出 --no-kv-offload）" },
  { key: "loadMode", label: "加载模式", type: "select", options: ["auto", "none", "mmap", "mlock", "mmap+mlock", "dio"], default: "auto", tab: "gpu", flag: "--load-mode", desc: "模型加载模式：mmap 内存映射 / mlock 锁定内存 / DirectIO；auto = 自动" },
  { key: "splitMode", label: "多卡切分模式", type: "select", options: ["layer", "none", "row", "tensor"], tab: "gpu", flag: "--split-mode", placeholder: "默认 layer", desc: "模型在多 GPU 间的切分方式：layer = 按层（默认）、row = 按行、tensor = 实验性" },
  { key: "tensorSplit", label: "GPU 分配比例", type: "text", tab: "gpu", flag: "-ts", placeholder: "如 3,1", desc: "每个 GPU 卸载的比例，逗号分隔，如 3,1" },
  { key: "mainGpu", label: "主 GPU", type: "number", min: 0, tab: "gpu", flag: "-mg", placeholder: "默认 0", desc: "主 GPU 索引（中间结果与 KV 所在卡）" },
  { key: "device", label: "指定设备", type: "text", tab: "gpu", flag: "-dev", placeholder: "如 0,1", desc: "用于卸载的设备列表（逗号分隔）；none = 不卸载" },
  { key: "cpuMoe", label: "MoE 权重留 CPU", type: "switch", tab: "gpu", flag: "-cmoe", desc: "全部 Mixture-of-Experts 权重保留在 CPU（省显存）" },
  { key: "nCpuMoe", label: "CPU MoE 层数", type: "number", min: 0, tab: "gpu", flag: "-ncmoe", desc: "前 N 层 MoE 权重保留在 CPU" },
  { key: "nCpuFfn", label: "CPU FFN 层数", type: "number", min: 0, tab: "gpu", flag: "-ncffn", desc: "前 N 层稠密 FFN 权重保留在 CPU" },
  { key: "numa", label: "NUMA 优化", type: "select", options: ["distribute", "isolate", "numactl"], tab: "gpu", flag: "--numa", desc: "NUMA 内存拓扑优化策略（部分多路服务器有效）" },
  { key: "noHost", label: "无 host 缓冲", type: "switch", tab: "gpu", flag: "--no-host", desc: "绕过 host buffer，允许使用额外缓冲" },
  { key: "swaFull", label: "SWA 全量缓存", type: "switch", tab: "gpu", flag: "--swa-full", desc: "使用全尺寸滑动窗口（SWA）缓存" },

  // —— 采样 ——
  { key: "temperature", label: "温度", type: "number", default: 0.8, step: 0.05, min: 0, tab: "sampling", flag: "--temp", desc: "采样温度，越高越随机（官方默认 0.80）" },
  { key: "topK", label: "Top-K", type: "number", default: 40, min: 0, tab: "sampling", flag: "--top-k", desc: "Top-K 采样，0 = 禁用（官方默认 40）" },
  { key: "topP", label: "Top-P", type: "number", default: 0.95, step: 0.01, min: 0, tab: "sampling", flag: "--top-p", desc: "核采样（Top-P），1.0 = 禁用（官方默认 0.95）" },
  { key: "minP", label: "Min-P", type: "number", default: 0.05, step: 0.01, min: 0, tab: "sampling", flag: "--min-p", desc: "Min-P 采样，0.0 = 禁用（官方默认 0.05）" },
  { key: "typical", label: "局部典型", type: "number", step: 0.05, min: 0, tab: "sampling", flag: "--typical-p", placeholder: "默认 1.0", desc: "Locally typical 采样，1.0 = 禁用" },
  { key: "topNsigma", label: "Top-N-Sigma", type: "number", min: -1, step: 0.1, tab: "sampling", flag: "--top-nsigma", placeholder: "默认 -1（禁用）", desc: "Top-N-sigma 采样，-1 = 禁用" },
  { key: "xtcProbability", label: "XTC 概率", type: "number", step: 0.05, min: 0, tab: "sampling", flag: "--xtc-probability", placeholder: "默认 0（禁用）", desc: "XTC（跨 token 条件）采样概率，0 = 禁用" },
  { key: "xtcThreshold", label: "XTC 阈值", type: "number", step: 0.05, min: 0, tab: "sampling", flag: "--xtc-threshold", placeholder: "默认 0.10", desc: "XTC 采样阈值，1.0 = 禁用" },
  { key: "repeatPenalty", label: "重复惩罚", type: "number", step: 0.01, min: 0, tab: "sampling", flag: "--repeat-penalty", placeholder: "默认 1.0", desc: "重复 token 序列惩罚，1.0 = 禁用" },
  { key: "repeatLastN", label: "惩罚窗口", type: "number", min: 0, tab: "sampling", flag: "--repeat-last-n", placeholder: "默认 64", desc: "惩罚考虑最近 n 个 token，0 = 禁用" },
  { key: "presencePenalty", label: "存在惩罚", type: "number", step: 0.01, min: 0, tab: "sampling", flag: "--presence-penalty", placeholder: "默认 0", desc: "重复 token 存在惩罚，0 = 禁用" },
  { key: "frequencyPenalty", label: "频率惩罚", type: "number", step: 0.01, min: 0, tab: "sampling", flag: "--frequency-penalty", placeholder: "默认 0", desc: "重复 token 频率惩罚，0 = 禁用" },
  { key: "dryMultiplier", label: "DRY 乘数", type: "number", step: 0.05, min: 0, tab: "sampling", flag: "--dry-multiplier", placeholder: "默认 0（禁用）", desc: "DRY（不要重复自己）采样乘数，0 = 禁用" },
  { key: "dryBase", label: "DRY 底值", type: "number", step: 0.05, min: 0, tab: "sampling", flag: "--dry-base", placeholder: "默认 1.75", desc: "DRY 采样底值" },
  { key: "dryAllowedLength", label: "DRY 允许长度", type: "number", min: 0, tab: "sampling", flag: "--dry-allowed-length", placeholder: "默认 2", desc: "DRY 采样允许的最大重复长度" },
  { key: "dryPenaltyLastN", label: "DRY 惩罚窗口", type: "number", min: 0, tab: "sampling", flag: "--dry-penalty-last-n", placeholder: "默认 64", desc: "DRY 对最近 n 个 token 的惩罚，0 = 禁用" },
  { key: "dynatempRange", label: "动态温度范围", type: "number", step: 0.05, min: 0, tab: "sampling", flag: "--dynatemp-range", placeholder: "默认 0（禁用）", desc: "动态温度范围，0 = 禁用" },
  { key: "dynatempExp", label: "动态温度指数", type: "number", step: 0.05, min: 0, tab: "sampling", flag: "--dynatemp-exp", placeholder: "默认 1.0", desc: "动态温度指数" },
  { key: "mirostat", label: "Mirostat", type: "select", options: ["0", "1", "2"], tab: "sampling", flag: "--mirostat", placeholder: "0 = 禁用", desc: "0 = 禁用、1 = Mirostat、2 = Mirostat 2.0" },
  { key: "mirostatLr", label: "Mirostat 学习率", type: "number", step: 0.01, min: 0, tab: "sampling", flag: "--mirostat-lr", placeholder: "默认 0.10", desc: "Mirostat 学习率（参数 eta）" },
  { key: "mirostatEnt", label: "Mirostat 熵", type: "number", step: 0.1, min: 0, tab: "sampling", flag: "--mirostat-ent", placeholder: "默认 5.00", desc: "Mirostat 目标熵（参数 tau）" },
  { key: "seed", label: "随机种子", type: "number", min: -1, tab: "sampling", flag: "-s", placeholder: "默认 -1（随机）", desc: "随机种子；-1 = 随机" },
  { key: "samplers", label: "采样器链", type: "text", tab: "sampling", flag: "--samplers", placeholder: "如 penalties;top_k;top_p;min_p;temperature", desc: "生成使用的采样器链（按顺序，分号分隔）" },
  { key: "ignoreEos", label: "忽略结束符", type: "switch", tab: "sampling", flag: "--ignore-eos", desc: "忽略 EOS 结束 token 继续生成" },

  // —— 上下文与 RoPE ——
  { key: "ropeScaling", label: "RoPE 缩放方式", type: "select", options: ["none", "linear", "yarn"], tab: "rope", flag: "--rope-scaling", placeholder: "默认 linear", desc: "RoPE 频率缩放方法；未指定时默认 linear（或模型指定值）" },
  { key: "ropeScale", label: "RoPE 缩放因子", type: "number", step: 0.5, min: 0, tab: "rope", flag: "--rope-scale", desc: "RoPE 上下文扩展因子（扩展 N 倍）" },
  { key: "ropeFreqBase", label: "RoPE 基础频率", type: "number", min: 0, tab: "rope", flag: "--rope-freq-base", placeholder: "默认取模型值", desc: "RoPE 基础频率（NTK-aware 缩放用）" },
  { key: "ropeFreqScale", label: "RoPE 频率因子", type: "number", step: 0.5, min: 0, tab: "rope", flag: "--rope-freq-scale", desc: "RoPE 频率缩放因子（扩展 1/N 倍）" },
  { key: "yarnOrigCtx", label: "YaRN 原始上下文", type: "number", min: 0, tab: "rope", flag: "--yarn-orig-ctx", placeholder: "默认 0", desc: "YaRN：模型原始训练上下文大小；0 = 模型训练上下文" },
  { key: "yarnExtFactor", label: "YaRN 外推因子", type: "number", step: 0.1, min: -1, tab: "rope", flag: "--yarn-ext-factor", placeholder: "默认 -1", desc: "YaRN：外推混合因子；0 = 全插值，-1 = 自动" },
  { key: "yarnAttnFactor", label: "YaRN 注意力因子", type: "number", step: 0.1, min: -1, tab: "rope", flag: "--yarn-attn-factor", placeholder: "默认 -1", desc: "YaRN：sqrt(t) 或注意力幅度缩放；-1 = 自动" },
  { key: "yarnBetaSlow", label: "YaRN beta-slow", type: "number", step: 0.1, min: -1, tab: "rope", flag: "--yarn-beta-slow", placeholder: "默认 -1", desc: "YaRN：高修正维度（alpha）；-1 = 自动" },
  { key: "yarnBetaFast", label: "YaRN beta-fast", type: "number", step: 0.1, min: -1, tab: "rope", flag: "--yarn-beta-fast", placeholder: "默认 -1", desc: "YaRN：低修正维度（beta）；-1 = 自动" },
  { key: "contextShift", label: "上下文位移", type: "switch", tab: "rope", flag: "--context-shift", desc: "无限长生成时启用上下文位移（默认禁用）" },

  // —— 投机解码 ——
  { key: "specType", label: "投机方式", type: "select", options: ["none", "draft-simple", "draft-eagle3", "draft-mtp", "draft-dflash", "draft-dspark", "ngram-simple", "ngram-map-k", "ngram-mod"], default: "none", tab: "spec", flag: "--spec-type", desc: "投机解码类型；draft-dflash/dspark 需另选 sidecar draft 模型" },
  { key: "specDraftModel", label: "Draft 模型", type: "select", dynamicOptions: "localGguf", tab: "spec", flag: "--spec-draft-model", placeholder: "选 DFlash/DSpark sidecar GGUF", desc: "投机解码 sidecar draft 模型（GGUF 路径）" },
  { key: "specDraftNMax", label: "投机步数", type: "number", default: 3, min: 0, tab: "spec", flag: "--spec-draft-n-max", desc: "每轮投机草稿 token 数（官方默认 3）" },
  { key: "specDraftNMin", label: "最小投机步数", type: "number", min: 0, tab: "spec", flag: "--spec-draft-n-min", placeholder: "默认 0", desc: "投机解码最少草稿 token 数" },
  { key: "specDraftPMin", label: "最小接受概率", type: "number", default: 1, step: 0.05, min: 0, tab: "spec", flag: "--spec-draft-p-min", desc: "投机解码（greedy）最小接受概率；1 = 严格贪心" },
  { key: "specDraftPSplit", label: "投机分裂概率", type: "number", step: 0.05, min: 0, tab: "spec", flag: "--spec-draft-p-split", placeholder: "默认 0.10", desc: "投机解码分裂概率" },
  { key: "specDraftNgl", label: "Draft GPU 层数", type: "number", min: 0, tab: "spec", flag: "-ngld", placeholder: "默认 auto", desc: "draft 模型放入显存的最大层数" },
  { key: "specDraftDevice", label: "Draft GPU 设备", type: "text", tab: "spec", flag: "-devd", placeholder: "如 0", desc: "draft 模型卸载设备列表（逗号分隔）" },

  // —— 服务与高级 ——
  { key: "host", label: "监听地址", type: "text", default: "0.0.0.0", tab: "server", flag: "--host", desc: "监听 IP；官方默认 127.0.0.1，此处默认 0.0.0.0 便于远程访问" },
  { key: "reasoning", label: "推理思考", type: "select", options: ["auto", "on", "off"], default: "auto", tab: "server", flag: "--reasoning", desc: "聊天启用推理/思考；auto = 从模板自动检测（官方默认 auto）" },
  { key: "reasoningFormat", label: "推理格式", type: "select", options: ["none", "deepseek", "deepseek-legacy"], tab: "server", flag: "--reasoning-format", placeholder: "默认 auto", desc: "思考内容的解析与返回格式" },
  { key: "reasoningEffort", label: "推理力度", type: "select", options: ["default", "minimal", "low", "medium", "high", "xhigh", "max"], tab: "server", flag: "--reasoning-effort", placeholder: "默认 default", desc: "传给聊天模板的推理力度级别" },
  { key: "jinja", label: "Jinja 模板", type: "switch", default: true, tab: "server", flag: "--no-jinja", desc: "聊天使用 jinja 模板引擎（默认启用；关闭时输出 --no-jinja）" },
  { key: "chatTemplate", label: "聊天模板", type: "text", tab: "server", flag: "--chat-template", placeholder: "如 chatml / vicuna 或自定义 Jinja", desc: "自定义聊天模板（内置模板名或 Jinja 模板）" },
  { key: "alias", label: "模型别名", type: "text", tab: "server", flag: "-a", desc: "API 对外显示的模型名（逗号分隔多个）" },
  { key: "apiKey", label: "API 密钥", type: "text", tab: "server", flag: "--api-key", desc: "API 认证密钥（多个逗号分隔）" },
  { key: "timeout", label: "读写超时", type: "number", min: 1, tab: "server", flag: "-to", placeholder: "默认 3600", desc: "服务器读/写超时（秒）" },
  { key: "threadsHttp", label: "HTTP 线程", type: "number", min: -1, tab: "server", flag: "--threads-http", placeholder: "默认 -1（自动）", desc: "处理 HTTP 请求的线程数" },
  { key: "cachePrompt", label: "提示词缓存", type: "switch", default: true, tab: "server", flag: "--no-cache-prompt", desc: "启用提示词 KV 缓存（默认启用；关闭时输出 --no-cache-prompt）" },
  { key: "cacheReuse", label: "缓存复用块", type: "number", min: 0, tab: "server", flag: "--cache-reuse", placeholder: "默认 0", desc: "KV 移位复用的最小块大小（需启用提示词缓存）" },
  { key: "slotPromptSimilarity", label: "槽位相似度", type: "number", step: 0.01, min: 0, tab: "server", flag: "-sps", placeholder: "默认 0.10", desc: "请求与槽位 prompt 相似度复用阈值；0 = 禁用" },
  { key: "webui", label: "Web UI", type: "switch", default: true, tab: "server", flag: "--no-ui", desc: "启用内置 Web UI（默认启用；关闭时输出 --no-ui）" },
  { key: "lora", label: "LoRA 适配器", type: "text", tab: "server", flag: "--lora", placeholder: "路径，多个逗号分隔", desc: "LoRA 适配器文件路径（可加载多个）" },
  { key: "overrideKv", label: "覆盖模型 KV", type: "text", tab: "server", flag: "--override-kv", placeholder: "如 tokenizer.ggml.add_bos_token=bool:false", desc: "按 key 覆盖模型元数据（int/float/bool/str，逗号分隔）" },
  { key: "extraArgs", label: "附加参数", type: "text", tab: "server", placeholder: "追加原始参数，如 --prio 1", desc: "追加到命令末尾的原始命令行参数（用于以上未列出的参数）" },
];
